import type { Metadata } from 'next'
import { ParticleConnectKit } from '@/components/ConnectKit'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import { Inder } from 'next/font/google'
import './globals.css'

const inder = Inder({ subsets: ['latin'], weight: '400' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inder.className}>
        <AntdRegistry>
          <ParticleConnectKit>{children}</ParticleConnectKit>{' '}
        </AntdRegistry>
      </body>
    </html>
  )
}
